### ISSUE TITLE
Ideology classic mode breaks much of the mod

### ISSUE THREAD

**Issue by jtgibson01** [Vanilla-Expanded/VanillaIdeologyExpanded-Memes#4]
While running Ideology in Classic mode (i.e., with Ideology still active in load order and Ideology gameplay features available, but choosing the "Classic mode" to disable all memes and ideologies for factions), many of the GameComponents, MapComponents, and Needs assume that the IdeoManager is active.  While it looks like some work has been made in null-checking at least, I notice nothing catches the classic mode.

I'm actually running on an externally-downloaded fork and am working against the 1.3 build, so uploading the changes might not be prudent (not to mention that with them now enforcing 2FA, this will likely be my last contribution to Github since I just don't trust Google enough... but I digress).  The changes are all basically identical, differing only in whether they need a return value or not.

1. In every `StatPart_*`, add `if(Find.IdeoManager.classicMode) return false;` as the first line under `public static bool Applies(Thing t)`
1. In every `MapComponent_*`, add `if(Find.IdeoManager.classicMode) return;` as the first line under `public override void MapComponentTick()`
1. In every `GameComponent_*`, add `if(Find.IdeoManager.classicMode) return;` as the first line under `public override void GameComponentTick()`
1. In the `IncidentWorker_JunkChunkDrop`, add `if(Find.IdeoManager.classicMode) return false;` as the first line under `protected override bool CanFireNowSub(IncidentParms parms)`
1. *(Game breakingly bad)* In `Need_Desserts`, add `if(Find.IdeoManager.classicMode) return false;` as the first line in the getter for `public override bool ShowOnNeedList`.  Missing this one breaks the Needs panel entirely for all pawns.
1. In `VanillaMemesExpanded_Plant_YieldNow_Patch`, you guessed it, `if(Find.IdeoManager.classicMode) return;`
1. Ditto `VanillaMemesExpanded_Command_SetPlantToGrow_IsPlantAvailable_Patch`
1. Ditto `VanillaMemesExpanded_LordToil_PanicFlee_Init_Patch`
1. Ditto `VanillaMemesExpanded_GenLeaving_GetBuildingResourcesLeaveCalculator_Patch`
1. And for a refreshing change of pace, in `CompDeconstructJunk`, break out of the enumerable with `if(Find.IdeoManager.classicMode) yield break;` as the first line under `public override IEnumerable<Gizmo> CompGetGizmosExtra()`

**Comment by juanosarg** [comment]
Thanks for the very comprehensive breakdown!
